/* === AIMRE — Données de démonstration === */

const DemoData = {
  'Propriétaires': [
    { _rowIndex: 2, ID: 'OWN001', Nom: 'ALTORIA', 'Contact principal': 'Jean Dupont', Email: 'contact@altoria.be', Téléphone: '+32 2 555 0001', Notes: '' },
    { _rowIndex: 3, ID: 'OWN002', Nom: 'LOUISE CENTER', 'Contact principal': 'Marie Claes', Email: 'info@louisecenter.be', Téléphone: '+32 2 555 0002', Notes: '' },
    { _rowIndex: 4, ID: 'OWN003', Nom: 'BLUE COLIBRI', 'Contact principal': 'Pierre Van den Berg', Email: 'info@bluecolibri.be', Téléphone: '+32 2 555 0003', Notes: '' },
    { _rowIndex: 5, ID: 'OWN004', Nom: 'GREEN SQUARE', 'Contact principal': 'Sophie Laurent', Email: 'info@greensquare.be', Téléphone: '+32 2 555 0004', Notes: '' },
    { _rowIndex: 6, ID: 'OWN005', Nom: 'CATELLAC', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 7, ID: 'OWN006', Nom: 'KREGLINGER', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 8, ID: 'OWN007', Nom: 'KANAM', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 9, ID: 'OWN008', Nom: 'SICORE17', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 10, ID: 'OWN009', Nom: 'TRAFIC', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 11, ID: 'OWN010', Nom: 'IROKO', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' },
    { _rowIndex: 12, ID: 'OWN011', Nom: 'LANDELL', 'Contact principal': '', Email: '', Téléphone: '', Notes: '' }
  ],

  'Immeubles': [
    { _rowIndex: 2, ID: 'BLD001', Nom: 'LE CORREGE N85', Propriétaire: 'ALTORIA', Adresse: 'Rue du Corrège 85, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '5000', 'Nombre de lots': '10', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 3, ID: 'BLD002', Nom: '100 LOUISE', Propriétaire: 'CATELLAC', Adresse: 'Avenue Louise 100, 1050 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '8000', 'Nombre de lots': '15', 'Lots vacants': '3', 'Photo URL': '' },
    { _rowIndex: 4, ID: 'BLD003', Nom: 'A50', Propriétaire: 'KREGLINGER', Adresse: 'Avenue des Arts 50, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '6000', 'Nombre de lots': '12', 'Lots vacants': '4', 'Photo URL': '' },
    { _rowIndex: 5, ID: 'BLD004', Nom: 'B12', Propriétaire: 'KREGLINGER', Adresse: 'Boulevard Bischoffsheim 12, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '4500', 'Nombre de lots': '8', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 6, ID: 'BLD005', Nom: 'J2E', Propriétaire: 'KREGLINGER', Adresse: 'Rue des 2 Églises 14-18, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '5500', 'Nombre de lots': '10', 'Lots vacants': '3', 'Photo URL': '' },
    { _rowIndex: 7, ID: 'BLD006', Nom: 'LOUISE CENTER', Propriétaire: 'LOUISE CENTER', Adresse: 'Avenue Louise, 1050 Bruxelles', Type: 'Mixte', 'Surface totale (m²)': '12000', 'Nombre de lots': '20', 'Lots vacants': '4', 'Photo URL': '' },
    { _rowIndex: 8, ID: 'BLD007', Nom: 'D78', Propriétaire: 'TRAFIC', Adresse: 'Rue de la Loi 78, 1040 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '3500', 'Nombre de lots': '6', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 9, ID: 'BLD008', Nom: '17 ATRIUM', Propriétaire: 'SICORE17', Adresse: 'Rue de la Science 17, 1040 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '15000', 'Nombre de lots': '25', 'Lots vacants': '5', 'Photo URL': '' },
    { _rowIndex: 10, ID: 'BLD009', Nom: 'GREEN SQUARE', Propriétaire: 'GREEN SQUARE', Adresse: 'Lambroekstraat 5, 1831 Diegem', Type: 'Bureau', 'Surface totale (m²)': '19530', 'Nombre de lots': '20', 'Lots vacants': '9', 'Photo URL': '' },
    { _rowIndex: 11, ID: 'BLD010', Nom: 'THE LIGHTHOUSE', Propriétaire: 'SICORE17', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '10000', 'Nombre de lots': '15', 'Lots vacants': '3', 'Photo URL': '' },
    { _rowIndex: 12, ID: 'BLD011', Nom: 'THE HUB', Propriétaire: 'SICORE17', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '8000', 'Nombre de lots': '12', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 13, ID: 'BLD012', Nom: 'BLUE COLIBRI', Propriétaire: 'BLUE COLIBRI', Adresse: 'Lambroekstraat 5, 1831 Diegem', Type: 'Bureau', 'Surface totale (m²)': '19530', 'Nombre de lots': '20', 'Lots vacants': '10', 'Photo URL': '' },
    { _rowIndex: 14, ID: 'BLD013', Nom: 'ALTORIA', Propriétaire: 'ALTORIA', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '7000', 'Nombre de lots': '12', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 15, ID: 'BLD014', Nom: '120 CURALIA', Propriétaire: 'CATELLAC', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '5000', 'Nombre de lots': '8', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 16, ID: 'BLD015', Nom: 'EXOS', Propriétaire: 'IROKO', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '4000', 'Nombre de lots': '6', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 17, ID: 'BLD016', Nom: 'ARCHIMEDE 61', Propriétaire: 'KANAM', Adresse: 'Rue Archimède 61, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '5500', 'Nombre de lots': '10', 'Lots vacants': '3', 'Photo URL': '' },
    { _rowIndex: 18, ID: 'BLD017', Nom: 'KENNEDY 8A', Propriétaire: 'KANAM', Adresse: 'Avenue Kennedy 8A, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '3000', 'Nombre de lots': '5', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 19, ID: 'BLD018', Nom: 'KENNEDY 8B', Propriétaire: 'KANAM', Adresse: 'Avenue Kennedy 8B, 1000 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '3000', 'Nombre de lots': '5', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 20, ID: 'BLD019', Nom: 'SOUTH CRYSTAL', Propriétaire: 'KREGLINGER', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '6000', 'Nombre de lots': '10', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 21, ID: 'BLD020', Nom: 'LOI67', Propriétaire: 'KREGLINGER', Adresse: 'Rue de la Loi 67, 1040 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '4000', 'Nombre de lots': '8', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 22, ID: 'BLD021', Nom: 'LOUISE 209', Propriétaire: 'KREGLINGER', Adresse: 'Avenue Louise 209, 1050 Bruxelles', Type: 'Bureau', 'Surface totale (m²)': '5000', 'Nombre de lots': '10', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 23, ID: 'BLD022', Nom: 'SAFRA', Propriétaire: 'KREGLINGER', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '3500', 'Nombre de lots': '6', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 24, ID: 'BLD023', Nom: 'IROKO', Propriétaire: 'IROKO', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '4500', 'Nombre de lots': '8', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 25, ID: 'BLD024', Nom: 'EXCELSIOR 33', Propriétaire: 'LANDELL', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '3000', 'Nombre de lots': '5', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 26, ID: 'BLD025', Nom: 'LANDELL', Propriétaire: 'LANDELL', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '4000', 'Nombre de lots': '7', 'Lots vacants': '2', 'Photo URL': '' },
    { _rowIndex: 27, ID: 'BLD026', Nom: 'L23', Propriétaire: 'LANDELL', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '2500', 'Nombre de lots': '4', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 28, ID: 'BLD027', Nom: 'TRAFIC', Propriétaire: 'TRAFIC', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '3000', 'Nombre de lots': '5', 'Lots vacants': '1', 'Photo URL': '' },
    { _rowIndex: 29, ID: 'BLD028', Nom: 'CATELLAC', Propriétaire: 'CATELLAC', Adresse: '', Type: 'Bureau', 'Surface totale (m²)': '6000', 'Nombre de lots': '10', 'Lots vacants': '2', 'Photo URL': '' }
  ],

  'Prospects': [
    { _rowIndex: 2, ID: 'P001', Immeuble: 'LE CORREGE N85', Propriétaire: 'ALTORIA', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'SIEMENS', Contact: '', Source: 'Broker', Statut: 'Nouveau', 'Date premier contact': '2026-01-15', 'Date dernière action': '2026-01-15', 'Prochaine action': '', 'Date prochaine action': '', Notes: '', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 3, ID: 'P002', Immeuble: '100 LOUISE', Propriétaire: 'CATELLAC', 'Lot / Unité': '', 'Surface (m²)': '250', 'Loyer demandé (€/mois)': '', 'Nom prospect': "O'CONNOR", Contact: '', Source: 'Broker', Statut: 'Visite effectuée', 'Date premier contact': '2026-02-20', 'Date dernière action': '2026-03-09', 'Prochaine action': 'Attendre retour après visite', 'Date prochaine action': '2026-03-20', Notes: 'Visite le 9/3/2026', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 4, ID: 'P003', Immeuble: '100 LOUISE', Propriétaire: 'CATELLAC', 'Lot / Unité': '', 'Surface (m²)': '250', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'EUROPEX', Contact: '', Source: 'Broker', Statut: 'Visite effectuée', 'Date premier contact': '2026-02-25', 'Date dernière action': '2026-03-09', 'Prochaine action': 'Suivi post-visite', 'Date prochaine action': '2026-03-18', Notes: 'Visite le 9/3/2026. Agent: CBRE (Julia Tattos)', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 5, ID: 'P004', Immeuble: 'A50', Propriétaire: 'KREGLINGER', 'Lot / Unité': '7è étage', 'Surface (m²)': '115.8', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'CITBLATON', Contact: '', Source: 'Broker', Statut: 'Offre reçue', 'Date premier contact': '2026-01-10', 'Date dernière action': '2026-02-06', 'Prochaine action': 'Relance pour retour proposition', 'Date prochaine action': '2026-03-10', Notes: 'Proposition locative envoyée le 6/2/2026. Durée bail : 2 ans. Agent: MESHI IMMO. En attente retour (115,8 m² au 7è étage)', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 6, ID: 'P005', Immeuble: 'A50', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'BRUSSELS SIGNALS', Contact: '', Source: 'Broker', Statut: 'Perdu', 'Date premier contact': '2026-02-15', 'Date dernière action': '2026-03-09', 'Prochaine action': '', 'Date prochaine action': '', Notes: 'Visite le 9/3/2026. Agent: KEY ESTATE. Pas de suite.', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 7, ID: 'P006', Immeuble: 'A50', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '100', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'EUROPEX', Contact: '', Source: 'Broker', Statut: 'Visite effectuée', 'Date premier contact': '2026-01-20', 'Date dernière action': '2026-02-04', 'Prochaine action': 'Suivi post-visite', 'Date prochaine action': '2026-03-15', Notes: 'Visite le 4/2/2026. Agent: COLLIERS.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 8, ID: 'P007', Immeuble: 'A50', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'TFBB', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-10', 'Prochaine action': 'Visite programmée', 'Date prochaine action': '2026-03-10', Notes: 'Visite le 10/3/2026. Agent: COLLIERS.', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 9, ID: 'P008', Immeuble: 'B12', Propriétaire: 'KREGLINGER', 'Lot / Unité': '6è étage', 'Surface (m²)': '329', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'CITBLATON', Contact: '', Source: 'Broker', Statut: 'Offre reçue', 'Date premier contact': '2026-01-10', 'Date dernière action': '2026-02-06', 'Prochaine action': 'Relance pour retour proposition', 'Date prochaine action': '2026-03-10', Notes: 'Proposition locative envoyée le 6/2/2026. Durée bail : 2 ans. Agent: MESHI IMMO. En attente retour (329 m² au 6è étage)', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 10, ID: 'P009', Immeuble: 'B12', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '329', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'RFI/RLS', Contact: '', Source: 'Broker', Statut: 'Offre reçue', 'Date premier contact': '2025-12-01', 'Date dernière action': '2026-01-15', 'Prochaine action': 'Suivi de l\'offre', 'Date prochaine action': '2026-02-15', Notes: 'Visite le 11/12/2025. Offre envoyée en janv. 2026. Agent: BATHIM.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 11, ID: 'P010', Immeuble: 'B12', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'EDSO', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-18', 'Prochaine action': 'Visite le 18/3/2026', 'Date prochaine action': '2026-03-18', Notes: 'Agent: BNPPRE (Geneviève Debaisieux).', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 12, ID: 'P011', Immeuble: 'J2E', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'BRUSSELS SIGNALS', Contact: '', Source: 'Broker', Statut: 'Offre reçue', 'Date premier contact': '2026-02-01', 'Date dernière action': '2026-03-01', 'Prochaine action': 'Suivi des options proposées', 'Date prochaine action': '2026-03-20', Notes: 'Offre envoyée. Option 1: 270 m² au 1er étage (2 Églises 14-16). Option 2: 300 m² au GF (2 Églises 18-20). Agent: KEY ESTATE.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 13, ID: 'P012', Immeuble: 'J2E', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'KAMILOU', Contact: '', Source: 'Réseau', Statut: 'Négociation', 'Date premier contact': '2025-06-01', 'Date dernière action': '2026-03-01', 'Prochaine action': 'Discussion extension', 'Date prochaine action': '2026-03-25', Notes: 'Déjà locataire. Souhaite une extension.', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 14, ID: 'P013', Immeuble: 'J2E', Propriétaire: 'KREGLINGER', 'Lot / Unité': '', 'Surface (m²)': '400-500', 'Loyer demandé (€/mois)': '', 'Nom prospect': '? (Prospect inconnu)', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-15', 'Date dernière action': '2026-03-15', 'Prochaine action': 'Visite le 26/3/2026', 'Date prochaine action': '2026-03-26', Notes: 'Agent: BNPPRE (Matteo Mollica). Visite le 26/3/2026.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 15, ID: 'P014', Immeuble: 'LOUISE CENTER', Propriétaire: 'LOUISE CENTER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'ALTAVIA', Contact: '', Source: '', Statut: 'Nouveau', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-01', 'Prochaine action': '', 'Date prochaine action': '', Notes: '', 'Responsable AIMRE': '' },
    { _rowIndex: 16, ID: 'P015', Immeuble: 'LOUISE CENTER', Propriétaire: 'LOUISE CENTER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'NATIONS UNIES', Contact: '', Source: '', Statut: 'Nouveau', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-01', 'Prochaine action': '', 'Date prochaine action': '', Notes: '', 'Responsable AIMRE': '' },
    { _rowIndex: 17, ID: 'P016', Immeuble: 'LOUISE CENTER', Propriétaire: 'LOUISE CENTER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'OMNIA', Contact: '', Source: '', Statut: 'Nouveau', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-01', 'Prochaine action': '', 'Date prochaine action': '', Notes: '', 'Responsable AIMRE': '' },
    { _rowIndex: 18, ID: 'P017', Immeuble: 'LOUISE CENTER', Propriétaire: 'LOUISE CENTER', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'GHX', Contact: '', Source: '', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-05', 'Date dernière action': '2026-03-15', 'Prochaine action': 'Seconde visite', 'Date prochaine action': '2026-03-19', Notes: 'Seconde visite le 19/3/2026', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 19, ID: 'P018', Immeuble: 'D78', Propriétaire: 'TRAFIC', 'Lot / Unité': '', 'Surface (m²)': '', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'TICC', Contact: '', Source: '', Statut: 'Visite effectuée', 'Date premier contact': '2026-02-20', 'Date dernière action': '2026-03-04', 'Prochaine action': 'Suivi post-visite', 'Date prochaine action': '2026-03-20', Notes: 'Visite le 4/3/2026', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 20, ID: 'P019', Immeuble: '17 ATRIUM', Propriétaire: 'SICORE17', 'Lot / Unité': '', 'Surface (m²)': '1000-1500', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'EURELECTRIC', Contact: '', Source: '', Statut: 'Visite planifiée', 'Date premier contact': '2026-02-15', 'Date dernière action': '2026-03-10', 'Prochaine action': 'Seconde visite le 19/3/2026', 'Date prochaine action': '2026-03-19', Notes: 'Visite / seconde visite le 19/3/2026', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 21, ID: 'P020', Immeuble: '17 ATRIUM', Propriétaire: 'SICORE17', 'Lot / Unité': '', 'Surface (m²)': '10000-12000', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'DEGROOF PETERCAM', Contact: '', Source: 'Broker', Statut: 'Contacté', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-04', 'Prochaine action': 'Planifier visite', 'Date prochaine action': '2026-03-25', Notes: 'Initial contact. Agent: CBRE.', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 22, ID: 'P021', Immeuble: 'GREEN SQUARE', Propriétaire: 'GREEN SQUARE', 'Lot / Unité': '', 'Surface (m²)': '1000-1200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'COLAS', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-18', 'Prochaine action': 'Visite le 18/3/2026', 'Date prochaine action': '2026-03-18', Notes: 'Début bail souhaité: 01/2028. Agent: CUSHMAN (Thomas Buggenhout).', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 23, ID: 'P022', Immeuble: 'THE LIGHTHOUSE', Propriétaire: 'SICORE17', 'Lot / Unité': '', 'Surface (m²)': '1000-1200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'COLAS', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-18', 'Prochaine action': 'Visite le 18/3/2026', 'Date prochaine action': '2026-03-18', Notes: 'Début bail souhaité: 01/2028. Agent: CUSHMAN (Thomas Buggenhout).', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 24, ID: 'P023', Immeuble: 'THE HUB', Propriétaire: 'SICORE17', 'Lot / Unité': '', 'Surface (m²)': '1000-1200', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'COLAS', Contact: '', Source: 'Broker', Statut: 'Visite planifiée', 'Date premier contact': '2026-03-01', 'Date dernière action': '2026-03-18', 'Prochaine action': 'Visite le 18/3/2026', 'Date prochaine action': '2026-03-18', Notes: 'Début bail souhaité: 01/2028. Agent: CUSHMAN (Thomas Buggenhout).', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 25, ID: 'P024', Immeuble: 'BLUE COLIBRI', Propriétaire: 'BLUE COLIBRI', 'Lot / Unité': 'C+D 1er', 'Surface (m²)': '3000', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'STELLANTIS', Contact: 'Romain Palm', Source: 'Broker', Statut: 'Négociation', 'Date premier contact': '2025-11-01', 'Date dernière action': '2026-02-15', 'Prochaine action': 'Suivi extension 200-400m²', 'Date prochaine action': '2026-03-20', Notes: 'Offre envoyée floors C et D 1er étage + terrasse + GF de C. Meeting extension 200-400m² tbc. Agent: Cushman & Wakefield.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 26, ID: 'P025', Immeuble: 'BLUE COLIBRI', Propriétaire: 'BLUE COLIBRI', 'Lot / Unité': '', 'Surface (m²)': '602', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'CANDOR', Contact: 'Dick de Keyser', Source: 'Broker', Statut: 'Négociation', 'Date premier contact': '2025-09-01', 'Date dernière action': '2026-02-01', 'Prochaine action': 'Attendre retour après extension co-working', 'Date prochaine action': '2026-03-31', Notes: 'Co-working étendu jusqu\'en juillet. Continue d\'évaluer les options. Agent: Key Estate.', 'Responsable AIMRE': 'Marine de Radiguès' },
    { _rowIndex: 27, ID: 'P026', Immeuble: 'BLUE COLIBRI', Propriétaire: 'BLUE COLIBRI', 'Lot / Unité': '', 'Surface (m²)': '260', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'MIDAM PRODUCTION', Contact: 'Romain Palm', Source: 'Broker', Statut: 'Perdu', 'Date premier contact': '2025-12-01', 'Date dernière action': '2026-02-01', 'Prochaine action': '', 'Date prochaine action': '', Notes: 'Ils vont finalement louer dans un co-working. Agent: Cushman & Wakefield.', 'Responsable AIMRE': 'Guillaume MEERT' },
    { _rowIndex: 28, ID: 'P027', Immeuble: 'BLUE COLIBRI', Propriétaire: 'BLUE COLIBRI', 'Lot / Unité': '', 'Surface (m²)': '250-300', 'Loyer demandé (€/mois)': '', 'Nom prospect': 'FIDI', Contact: 'Joffrey Stros', Source: 'Broker', Statut: 'Offre reçue', 'Date premier contact': '2026-01-15', 'Date dernière action': '2026-01-20', 'Prochaine action': 'Suivi offre — bail début avril 2027', 'Date prochaine action': '2026-04-01', Notes: 'Offre envoyée. Début bail: avril 2027. Parkings: 6. Durée: 6/9. Agent: Elias Partner (Joffrey Stros).', 'Responsable AIMRE': 'Marine de Radiguès' }
  ],

  'Utilisateurs': [
    { _rowIndex: 2, Email: 'gm@aimre.com', Nom: 'Guillaume MEERT', Rôle: 'Admin', Actif: 'Oui' },
    { _rowIndex: 3, Email: 'mdr@aimre.com', Nom: 'Marine de Radiguès', Rôle: 'Editeur', Actif: 'Oui' }
  ]
};
